services:
  - type: web
    name: hellfire-auctions
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: "3000"
      - key: HOST
        value: "0.0.0.0"
      - key: DATABASE_URL
        fromDatabase:
          name: hellfire-auctions-db
          property: connectionString
      - key: SCOPES
        value: write_metaobject_definitions,write_metaobjects,write_products,write_publications,read_inventory,write_inventory,read_locations,write_draft_orders,write_app_proxy
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false

databases:
  - name: hellfire-auctions-db
    plan: free
    databaseName: hellfire_auctions
