# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb49cba90749e254b957cd1d618e6d38"
application_url = "https://hellfire-auctions.onrender.com"
embedded = true
name = "Hellfire Auctions"

[access_scopes]
scopes = "write_products,write_publications,read_inventory,write_inventory,read_locations,write_draft_orders,write_app_proxy,read_customers,write_online_store_navigation"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/subscriptions_update"
  topics = [ "app_subscriptions/update" ]

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[auth]
redirect_urls = [ "https://hellfire-auctions.onrender.com/auth/callback" ]

[build]
automatically_update_urls_on_dev = false

[app_proxy]
url = "/api/proxy"
prefix = "apps"
subpath = "hellfire-auctions"

